SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE study_user_groups_autosave;
TRUNCATE TABLE study_user_groups;
TRUNCATE TABLE study_screener_questions;

TRUNCATE TABLE study_user_groups;
TRUNCATE TABLE study_group_sessions_autosave;
TRUNCATE TABLE study_group_sessions;
TRUNCATE TABLE study_locations_autosave;
TRUNCATE TABLE study_locations;
TRUNCATE TABLE study_participants;
TRUNCATE TABLE study_user_groups;
TRUNCATE TABLE study_dnq;
TRUNCATE TABLE studies_autosave;
TRUNCATE TABLE studies;
TRUNCATE TABLE participant_usergroup_autosave;
TRUNCATE TABLE participant_usergroup_ug;
TRUNCATE TABLE `schedule`;
TRUNCATE TABLE schedule_details;
TRUNCATE TABLE locations;
TRUNCATE TABLE clients;
TRUNCATE TABLE contacts;
TRUNCATE TABLE ethnicities;
TRUNCATE TABLE classifications;
TRUNCATE TABLE participant_conditions_autosave;
TRUNCATE TABLE participant_conditions_ug;
TRUNCATE TABLE participant_employers;
TRUNCATE TABLE participant_notes;
TRUNCATE TABLE participant_occupations;
TRUNCATE TABLE participant_occupations_autosave;
TRUNCATE TABLE participant_occupations_ug;
TRUNCATE TABLE participant_photolog;
TRUNCATE TABLE participant_photolog_autosave;
TRUNCATE TABLE participant_usergroup_autosave;
TRUNCATE TABLE participant_usergroup_ug;
TRUNCATE TABLE participants;
TRUNCATE TABLE participants_autosave;
TRUNCATE TABLE participant_notes;
TRUNCATE TABLE participant_notes;
TRUNCATE TABLE participant_notes;
TRUNCATE TABLE participant_notes;

TRUNCATE TABLE products;

TRUNCATE TABLE user_groups;